// <auto-generated />
using DataAccess.Concrete.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Entities.Concrete.Kategori", b =>
                {
                    b.Property<int>("KategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("KategoriId");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            KategoriId = 1,
                            KategoriAdi = "Furniture"
                        },
                        new
                        {
                            KategoriId = 2,
                            KategoriAdi = "Electronics"
                        },
                        new
                        {
                            KategoriId = 3,
                            KategoriAdi = "Books"
                        },
                        new
                        {
                            KategoriId = 4,
                            KategoriAdi = "Accessories"
                        },
                        new
                        {
                            KategoriId = 5,
                            KategoriAdi = "Computers"
                        },
                        new
                        {
                            KategoriId = 6,
                            KategoriAdi = "Cameras"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.Urun", b =>
                {
                    b.Property<int>("UrunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("UrunFiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UrunResmi")
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<int>("UrunStok")
                        .HasColumnType("int");

                    b.HasKey("UrunId");

                    b.HasIndex("KategoriId");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            UrunId = 1,
                            IsFeatured = false,
                            KategoriId = 6,
                            UrunAdi = "Photo Camera",
                            UrunFiyati = 153m,
                            UrunResmi = "product1",
                            UrunStok = 220
                        },
                        new
                        {
                            UrunId = 2,
                            IsFeatured = false,
                            KategoriId = 4,
                            UrunAdi = "Wood Chair",
                            UrunFiyati = 99m,
                            UrunResmi = "product2",
                            UrunStok = 302
                        },
                        new
                        {
                            UrunId = 3,
                            IsFeatured = false,
                            KategoriId = 4,
                            UrunAdi = "Comfortable Sofa",
                            UrunFiyati = 526m,
                            UrunResmi = "product3",
                            UrunStok = 693
                        },
                        new
                        {
                            UrunId = 4,
                            IsFeatured = false,
                            KategoriId = 4,
                            UrunAdi = "Hand Bag",
                            UrunFiyati = 125m,
                            UrunResmi = "product4",
                            UrunStok = 56
                        });
                });

            modelBuilder.Entity("Entities.Concrete.Urun", b =>
                {
                    b.HasOne("Entities.Concrete.Kategori", "Kategori")
                        .WithMany("Urunler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("Entities.Concrete.Kategori", b =>
                {
                    b.Navigation("Urunler");
                });
#pragma warning restore 612, 618
        }
    }
}
